Task/FCT2-21477 enforce standardised dotnet formatting (#203)
* add pre-commit config and dotnet format hook

* run dotnet format

* add dotnet format check to PR pipeline

* update readme

diff --git a/devops-pipelines/templates/dotnet-build-steps.yml b/devops-pipelines/templates/dotnet-build-steps.yml
--- a/devops-pipelines/templates/dotnet-build-steps.yml
+++ b/devops-pipelines/templates/dotnet-build-steps.yml
@@ -5,6 +5,7 @@ parameters:
   dotNetVersion: '10.x'
   publishOutput: false
   runTests: false
+  checkFormatting: false
   testResultsDirectory: ''
 
 steps:
@@ -20,6 +21,31 @@ steps:
     inputs:
       command: 'restore'
       projects: '${{ parameters.projectPath }}'
+
+  # Check formatting
+  - ${{ if eq(parameters.checkFormatting, true) }}:
+      - task: Bash@3
+        displayName: "Check Formatting"
+        inputs:
+          targetType: "inline"
+          script: |
+            set +e
+
+            echo "Checking for any dotnet formatting issues..."
+
+            output=$(
+              dotnet format ${{ parameters.projectPath }} --no-restore --verify-no-changes 2>&1)
+            exit_code=$?
+
+            echo "$output"
+
+            if [ $exit_code -ne 0 ]; then
+              echo "##vso[task.logissue type=error]dotnet format found formatting issues. Please run 'dotnet format ${{ parameters.projectPath }}' and commit the changes."
+              exit $exit_code
+            else
+              echo "No formatting issues were found."
+              exit $exit_code
+            fi
 
   # Build project
   - task: DotNetCoreCLI@2
@@ -62,5 +88,5 @@ steps:
         arguments: '--configuration ${{ parameters.buildConfiguration }} --output $(Build.ArtifactStagingDirectory)/${{ parameters.projectName }} --no-restore --self-contained false /p:PublishReadyToRun=false /p:SourceRevisionId=$(Build.SourceVersion)'
 
     - publish: '$(Build.ArtifactStagingDirectory)/${{ parameters.projectName }}'
-      artifact: '${{ parameters.projectName }}' 
-      displayName: 'Publish ${{ parameters.projectName }} Artifact'   
+      artifact: '${{ parameters.projectName }}'
+      displayName: 'Publish ${{ parameters.projectName }} Artifact'
